import { ISection } from ".";

export const CARRIER: ISection = {
  title: "【重要】キャリア形成",
  description:
    "本レッスンでは、前半に「就職活動で自分にあった会社を選び、入社するために必要なマインド」を、\n" +
    "後半には「会社で出世、または経済的に大きな成功を収めるために必要なマインド」を身につけることができます。",
  contentsList: [
    {
      title: "Yahoo! JAPAN 内定者が教える就活講座",
      link: "https://youtu.be/Z6GTHCcI5sQ",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 8,
    },
    {
      title: "落ちないエントリーシートの書き方",
      link: "https://youtu.be/lqYQkIoBUoE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title:
        "いつから就活を始めるべきか？インターンには行くべきか？就活はどう動くべきか？",
      link: "https://youtu.be/t2dqLpilZ8E",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 14,
    },
    {
      title: "最強の情報収集力を手に入れる方法は「Feedly」を使うこと！",
      link: "https://youtu.be/pDb3Q19hVno",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 17,
    },
    {
      title: "20代の間に身につけておきたいスキル7選",
      link: "https://youtu.be/yXuQ9qkT-T8",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title:
        "ブラック企業とホワイト企業の違いをビジネスモデルと収益構造から分析しよう！",
      link: "https://youtu.be/d_hP9U4xmEs",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "好きな仕事を見つける方法",
      link: "https://youtu.be/wVM1GFz9DVs",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "企業の選び方！就職活動・転職活動で後悔しない会社選びをしよう！",
      link: "https://youtu.be/xlmG9RUmH_Y",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 13,
    },
    {
      title: "科学的な適職｜幸せホルモン分泌しまくりハッピー職業の正体とは？",
      link: "https://youtu.be/KcUyFrb5cf4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title:
        "【やりたいことの見つけ方①】人生のモヤモヤから解放される自己理解メソッド",
      link: "https://youtu.be/sk23TqDytzI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 40,
    },
    {
      title: "【やりたいことの見つけ方②】情熱×才能を仕事の目的で絞る",
      link: "https://youtu.be/4KTC2TF2WsY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 38,
    },
    {
      title:
        "【キャリアの悩みの処方箋】仕事のモヤモヤを解消する「文字セラピー」",
      link: "https://youtu.be/gNjauEf9t7c",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 5,
    },
    {
      title: "あなたが成功できるかどうか判定できる「たった2つ」の質問",
      link: "https://youtu.be/GwoNtIt85hY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 18,
    },
    {
      title: "あな本当の「安定」を生み出すたった1つのもの",
      link: "https://youtu.be/hLlot_iJU-I",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 17,
    },
    {
      title: "転職“未”経験者の評価が低くなる3つの理由",
      link: "https://youtu.be/aFwiAVqOI1w",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 14,
    },
    {
      title: "転職エージェントを利用する”前”に知っておくべき重要ポイント8選",
      link: "https://youtu.be/VRIXgDPhhUw",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "当てはまったらヤバイ、リストラ候補の特徴5選",
      link: "https://youtu.be/D-vYn6hfdvw",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 22,
    },
    {
      title:
        "３つの蓄積をしないと将来ヤバい。40代以下は全員必読。人生100年時代の攻略本",
      link: "https://youtu.be/SJjQ5M-kqb4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title: "副収入よりも大きな副業のメリット",
      link: "https://youtu.be/Feal8fLwLuU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "エンジニアのリアルな副業事情",
      link: "https://youtu.be/A2TjIAj_aWg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "副業で月5万円稼ぐための9つのポイント",
      link: "https://youtu.be/bAwoXkzvwdU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "副業に興味がある人は絶対に身に着けておくべき３つのスキル",
      link: "https://youtu.be/RC6PAXpysCk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "簿記3級・2級の学習を始めるのに「最適な時期」とその理由",
      link: "https://youtu.be/G-chS7B1czQ",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 17,
    },
    {
      title: "転職と副業のかけ算 ～生涯年収を最大化する生き方～",
      link: "https://youtu.be/5-iG9sS-l3A",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
    {
      title: "目標を達成するためのメンタルの作り方",
      link: "https://youtu.be/9c41Parq39s",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "好きなことを仕事にしないと貧困になる理由",
      link: "https://youtu.be/1dgpecnLKX4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 35,
    },
    {
      title:
        "「心のブレーキ」の外し方～仕事とプライベートに効く7つの心理セラピー",
      link: "https://youtu.be/JVM2Vp4CvT4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "シナジー人脈術 最小限の力で最大限の成果を生み出すたった1つの方法",
      link: "https://youtu.be/46NyPOnSNBo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "ギブしときゃ成功する、わけない",
      link: "https://youtu.be/dLCtXHvS3lc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "「信頼口座」の残高を増やすアクション5選",
      link: "https://youtu.be/tobtVkOEOBc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "「お金持ち」の考え方と、「貧乏人」の考え方の決定的な違い",
      link: "https://youtu.be/CXIM1x9vswM",
      mediaType: ["READ_ONLY", "RADIO"],
      requiredTime: 11,
    },
    {
      title: "不幸になりたくない人が最重視すべきたった1つのこと",
      link: "https://youtu.be/v03ONJrQOPo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "決断力がない人の特徴5選",
      link: "https://youtu.be/RBzmP4AzH2k",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 14,
    },
    {
      title: "捨てられない人は伸びません",
      link: "https://youtu.be/9CUJr0YbgqU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "サボり思考のススメ",
      link: "https://youtu.be/Z_fru_1rBqs",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 8,
    },
    {
      title: "1440分の使い方──成功者たちの時間管理15の秘訣",
      link: "https://youtu.be/OStLPiRjTv4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "エッセンシャル思考①【8割捨てろ】",
      link: "https://youtu.be/BA9n_JJEcwI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "エッセンシャル思考②【見極める技術】",
      link: "https://youtu.be/rxjsGJWGTpU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
    {
      title: "エッセンシャル思考③【仕事を捨てる２STEP】",
      link: "https://youtu.be/xNk3ziBreBA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "エッセンシャル思考④【エッセンシャルなチームをつくる！若手でも】",
      link: "https://youtu.be/IwFfFZfwYP0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 26,
    },
    {
      title: "【ハマりがち】成功を遠ざける「時給思考」の5つの罠",
      link: "https://youtu.be/U6PKth3F_9o",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "仕事が遅い人がやっていること",
      link: "https://youtu.be/vjZE93xyPnU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 17,
    },
    {
      title: "仕事が遅い人の3つの特徴",
      link: "https://youtu.be/wKRzvn8H49I",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "これから伸びる人、淘汰される人",
      link: "https://youtu.be/LW8yEo-i2sE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "人生は、運よりも実力よりも「勘違いさせる力」で決まっている",
      link: "https://youtu.be/PP_S6zZnVgw",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "劇的に人生を変える方法は2つしかない",
      link: "https://youtu.be/5NFHH6oW0qQ",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
    {
      title: "夢が叶わない理由は○○です",
      link: "https://youtu.be/R0Jo8J2wOog",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 6,
    },
    {
      title: "夢を叶えるためにあなたが取るべき行動TOP５",
      link: "https://youtu.be/d8unKZRi2eE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 22,
    },
    {
      title: "感動の条件",
      link: "https://youtu.be/bBa8Rg_pxu8",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "「礼儀正しさ」こそ最強の生存戦略である",
      link: "https://youtu.be/PRgeqbffjYM",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "オリエンタルランドから学ぶ「弱者の戦い方」",
      link: "https://youtu.be/AfzktlfpTY8",
      mediaType: ["READ_ONLY", "RADIO"],
      requiredTime: 11,
    },
    {
      title: "7つの習慣",
      link: "https://youtu.be/eVvci3WbJN0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "金持ちになりたい人が絶対に聞くべき小話「魔法のザクロ」",
      link: "https://youtu.be/DlA9lZq81DQ",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "「不安で動けない人」と「不安をコントロールできる人」の5つの違い ",
      link: "https://youtu.be/46Mo1Emcs80",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "【名著解説】あなたの不安を確実に消す思考法３選",
      link: "https://youtu.be/0YBWkn5Cesg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "仕事ができない人の特徴TOP5",
      link: "https://youtu.be/A8gHtvh8OKo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "凡人で終わる人の悪い習慣TOP５",
      link: "https://youtu.be/xGkMV0jAjZE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "【習慣術】時間を増やすために絶対やるべき習慣10選",
      link: "https://youtu.be/-t8Sef5wFGs",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 22,
    },
    {
      title: "あなたが挑戦すべきことTOP5",
      link: "https://youtu.be/eNunOPOYdes",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 23,
    },
    {
      title: "デキる人はみんなやってる決定疲れを防ぐ方法",
      link: "https://youtu.be/Ds5o-CBApF0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
    {
      title: "知らないと損するお金に関する3つの心理",
      link: "https://youtu.be/kSgXWyJ34uE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 23,
    },
    {
      title: "お金持ちになりたくない人がする行動5つ",
      link: "https://youtu.be/uMps1aLrHkA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "貧乏な人によくある勘違いTOP3",
      link: "https://youtu.be/cxxjNRXdiq8",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 13,
    },
    {
      title: "簡単に年収を上げる方法、僕らはどのように生きればよいか？",
      link: "https://youtu.be/PXNuV34z0O0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "あなたを幸せにするお金の使い方4選",
      link: "https://youtu.be/-fhNuVeOQjo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 13,
    },
    {
      title: "一生貧乏な人の特徴&解決策５選",
      link: "https://youtu.be/jlNBUE2vKiY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "自己投資を「成功に結びつける人」と「時間のムダにする人」の違い",
      link: "https://youtu.be/3baYoUB-vIQ",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 18,
    },
    {
      title: "サラリーマンが20％OFFで自己投資する方法【教育訓練給付金】",
      link: "https://youtu.be/n5W2OCg2urM",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "これからのお金の教科書",
      link: "https://youtu.be/DITX9pov_v0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 14,
    },
    {
      title: "なぜ「格差」は開くのか？その背景を知り格差に立ち向かおう",
      link: "https://youtu.be/9pEd9WjEDK4",
      mediaType: ["READ_ONLY", "RADIO"],
      requiredTime: 20,
    },
    {
      title: "お金の秘密：追えば追うほど、お金は逃げる！",
      link: "https://youtu.be/sRzFo3rwvhE",
      mediaType: ["READ_ONLY", "RADIO"],
      requiredTime: 28,
    },
    {
      title: "金持ちになるにはレバレッジを使え！",
      link: "https://youtu.be/sfOQ-W39SUA",
      mediaType: ["READ_ONLY", "RADIO"],
      requiredTime: 21,
    },
    {
      title: "永遠に幸せを感じる唯一の方法",
      link: "https://youtu.be/hz5hzMmhotE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 13,
    },
    {
      title: "人にプレゼントしたもの13選＆プレゼントする時の3つのコツ",
      link: "https://youtu.be/GRzE-TB0-hw",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 24,
    },
    {
      title: "自己投資の効果を爆上げする方法",
      link: "https://youtu.be/f27aOOZzOY8",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "アタマがみるみるシャープになる! 脳の強化書",
      link: "https://youtu.be/VOYapqswDzE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 14,
    },
    {
      title: "脳の処理速度を上げる方法(今すぐゲームをしろ！)",
      link: "https://youtu.be/4sVbBiuTq_I",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "科学的に幸せになれる脳磨き",
      link: "https://youtu.be/gjYCdzElj_0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 27,
    },
    {
      title: "絶対にミスをしない人の脳の習慣",
      link: "https://youtu.be/rUK6Ki9xYoc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
  ],
};
