import { ISection } from ".";

export const HTML: ISection = {
  title: "HTML && CSS",
  description:
    "Webページ作成の基礎となる、HTMLとCSSの初歩を学ぶレッスンです。\n" +
    "最終的にはBootstrapというHTMLフレームワークを使って、簡単なWebページを作成します。",
  contentsList: [
    {
      title: "非エンジニアでもわかる！Webサービス・アプリが動く仕組み",
      link: "https://youtu.be/zq50JwOU_ls",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "HTML&CSS初級編",
      link: "https://prog-8.com/html/study/1/1",
      mediaType: [],
      requiredTime: 230,
    },
    {
      title: "HTML基礎 HTMLの仕組み編",
      link: "https://codeprep.jp/books/123",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "メタタグとは？SEO効果は？metaタグ一覧と書き方まとめ",
      link: "https://saruwakakun.com/html-css/basic/meta-tag",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "HTMLのlinkタグとは？基本的な書き方とrel属性まとめ",
      link: "https://saruwakakun.com/html-css/basic/link-rel",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "ead内に書くべきタグを総まとめ：SEO対策に有効なものは？",
      link: "https://saruwakakun.com/html-css/basic/head",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "Twitterカードとは？使い方と設定方法まとめ",
      link: "https://saruwakakun.com/html-css/reference/twitter-card",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "HTML入門 基本要素(タグ)編",
      link: "https://codeprep.jp/books/1",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "HTML入門 HTML5編",
      link: "https://codeprep.jp/books/75",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "CSS入門 基本スタイリング編",
      link: "https://codeprep.jp/books/2",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "CSS入門 色の理論編",
      link: "https://codeprep.jp/books/16",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "CSS入門 CSS3編",
      link: "https://codeprep.jp/books/17",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "CSS入門 margin padding編",
      link: "https://codeprep.jp/books/49",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "CSS入門 position編",
      link: "https://codeprep.jp/books/64",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "CSS入門 display編",
      link: "https://codeprep.jp/books/73",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "Transform（変形）関連のまとめ",
      link: "https://qiita.com/7968/items/eddfeb4b424d7c2d2d34",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "Transition（変化）関連のまとめ",
      link: "https://qiita.com/7968/items/812d6a21fc4dd9ae9c75",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "z-indexのベストプラクティスを考える",
      link: "https://zenn.dev/catnose99/articles/2f1be29dd203c10dff01",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "画像の遅延読込に役立つamp-imgの使い方",
      link: "https://ics.media/entry/18237/",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "新プロパティmix-blend-modeを使いこなそう",
      link: "https://ics.media/entry/7258/",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "position: stickyの面白い使い方と使用時の注意点",
      link: "https://parashuto.com/rriver/development/position-sticky",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "CSSでできる色々な影の表現と意外に知らない落とし穴",
      link: "https://ics.media/entry/200406/",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "CSSで中央寄せする9つの方法（縦・横にセンタリング）",
      link: "https://saruwakakun.com/html-css/basic/centering",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "メディアクエリの「メディアタイプ」を理解しよう(前編) ",
      link: "https://youtu.be/79Dr3RGm0SI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "メディアクエリの「メディアタイプ」を理解しよう(後編) ",
      link: "https://youtu.be/B8LnpwiiOzE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "最強に便利なCSSの比較関数 min, max, clamp を紹介！",
      link: "https://youtu.be/oXHmEK_z-lo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title:
        "なんとなくで書かないで！HTML5を書く時に気にしてみたいタグごとのお約束",
      link: "https://qiita.com/mikimhk/items/05b303d932093eb4c0d1",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "HTML＆CSSでつくるグリッドレイアウト",
      link: "https://codeprep.jp/books/8",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "HTML＆CSSでつくるナビゲーションバー",
      link: "https://codeprep.jp/books/10",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "HTML＆CSSでつくるWebページ",
      link: "https://codeprep.jp/books/12",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "HTML&CSSでつくるドロップダウンメニュー",
      link: "https://codeprep.jp/books/18",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "HTML&CSS3でつくるポップなメニュー",
      link: "https://codeprep.jp/books/19",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "HTML&CSSでつくるモーダルウィンドウ",
      link: "https://codeprep.jp/books/41",
      mediaType: [],
      requiredTime: 25,
    },
    {
      title: "HTML&CSSでつくる登録フロー",
      link: "https://codeprep.jp/books/47",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "HTMLとCSSで作るWeb名刺",
      link: "https://codeprep.jp/books/50",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "HTMLとCSS3でつくるクルクル回転するローディング",
      link: "https://codeprep.jp/books/63",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "HTMLとCSS3でつくるお天気パネル",
      link: "https://codeprep.jp/books/77",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "HTMLとCSS3でつくるトグルスイッチ",
      link: "https://codeprep.jp/books/82",
      mediaType: [],
      requiredTime: 10,
    },
    {
      title: "HTMLとCSS3でつくるパンくず",
      link: "https://codeprep.jp/books/85",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "HTMLとCSS3でつくるホバー時に動くア二メーションリンク",
      link: "https://codeprep.jp/books/89",
      mediaType: [],
      requiredTime: 10,
    },
    {
      title: "HTMLとCSS3で作る通知ベル",
      link: "https://codeprep.jp/books/92",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "HTMLとCSS3で作るサイドメニュー",
      link: "https://codeprep.jp/books/97",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "HTMLとCSS3で作るホバー時に動くアニメーションボタン",
      link: "https://codeprep.jp/books/108",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "動画を使って夏らしいWebページを作ろう！",
      link: "https://codeprep.jp/books/112",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "フレックスボックス (flexbox) の使い方をゲームで学ぼう！",
      link: "https://youtu.be/FU4RocY_Y1k",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 30,
    },
    {
      title: "FLEXBOX FROGGY",
      link: "https://flexboxfroggy.com/#ja",
      mediaType: [],
      requiredTime: 30,
    },
    {
      title: "flexbox の flex プロパティの使い方を徹底解説",
      link: "https://youtu.be/TXwY_SWO07U",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "聖杯レイアウトのコーディング実践、デザイン解説",
      link: "https://youtu.be/XrFD_0Pr6Nc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title: "Gridを使うとFlexboxより簡単に複雑なレイアウトを組めます",
      link: "https://youtu.be/cwkkD0ejX8Q",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title:
        "よく使われるサイドバーデザインを一緒にコーディングしていきましょう",
      link: "https://youtu.be/UUPSC8ooDOk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "ハンバーガーメニューの作り方講座",
      link: "https://youtu.be/9XVuUr4DbNU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 35,
    },
    {
      title:
        "ハンバーガーメニューは実は悪いデザイン？代わりになるWebデザインを紹介します",
      link: "https://youtu.be/OOIz2nl5524",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 30,
    },
    {
      title: "下タブ（Bottom Navigation）のコーディング実践",
      link: "https://youtu.be/NDj9awgjEu0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "はじめてのBootstrap",
      link: "https://codeprep.jp/books/51",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "Bootstrapのグリッドシステムを理解する",
      link: "https://codeprep.jp/books/55",
      mediaType: [],
      requiredTime: 15,
    },
    {
      title: "Bootstrapで作る登録フォーム",
      link: "https://codeprep.jp/books/53",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "Bootstrapで作るWebページ",
      link: "https://codeprep.jp/books/57",
      mediaType: [],
      requiredTime: 30,
    },
    {
      title: "ITエンジニアの就活準備編2: ポートフォリオ制作",
      link: "https://paiza.jp/works/career/primer/career2",
      mediaType: ["VIDEO"],
      requiredTime: 80,
    },
    {
      title:
        "フロントエンドエンジニアとして、働くまでに作るべき5つのポートフォリオ",
      link: "https://youtu.be/nGt7utxF8OY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title:
        "Chrome DevToolsの使い方を徹底解説！Chrome Developer Toolsを使いこなすと開発効率が上がる！",
      link: "https://youtu.be/awRkFcv51r4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 30,
    },
  ],
};
