import { ISection } from ".";

export const LOGICAL_THINKING: ISection = {
  title: "ロジカルシンキング",
  description:
    "ロジカルシンキングとは、物事を体系的に整理して筋道を立て、矛盾なく考える思考法のこと。\n" +
    "この思考法はコンテストや高専祭のアイデア出しで使えることはもちろん、\n" +
    "普段のコミュニケーションで活用することで「コイツ、出来る！！」って思ってもらえるなどの効果があります。\n" +
    "このように幅広いケースで活用できる思考法なので、しっかり勉強して、できるビジネスマンに近づいていきましょう！\n",
  contentsList: [
    {
      title: "天才を殺す凡人｜世界の命運は凡人が握っていた",
      link: "https://youtu.be/X_7SPr_DyHE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 18,
    },
    {
      title: "凡人が「秀才」に明日から変わる方法",
      link: "https://youtu.be/c31WvhqpDxw",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 7,
    },
    {
      title: "行動が結果を変えるハック大学式最強の仕事術",
      link: "https://youtu.be/Qs4PpbR36ug",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "エンジニア式「ロジカルシンキング」の方法",
      link: "https://youtu.be/j3CCrHMZW3Q",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "エンジニア流「問題解決」の方法",
      link: "https://youtu.be/ISuh6pEDtGY9",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 13,
    },
    {
      title: "ロジカルシンキングの武器① ロジックツリー",
      link: "https://youtu.be/smPJdXwbWfE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "ロジカルシンキングの武器① ピラミッドストラクチャー",
      link: "https://youtu.be/zX5LyLqkl28",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 7,
    },
    {
      title: "「勉強になった！」で終わらない方法",
      link: "https://youtu.be/X25Kr56M0Kg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "優秀な人は具体と抽象の往復をする",
      link: "https://youtu.be/FjZGSBGB8Lc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "メモの魔力｜みんなが知らない2種類のメモ",
      link: "https://youtu.be/1h8vTIRJpdc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "仕事遅いやつ 仮説持ててない説",
      link: "https://youtu.be/3vBiOVcwlAs",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "因数分解すれば大体の仕事はうまくいく",
      link: "https://youtu.be/y_yg76oNiPY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "『数字に強い』は作れる",
      link: "https://youtu.be/wMpQqZeGjsI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "地頭力を鍛える 問題解決に活かす「フェルミ推定」/前編",
      link: "https://youtu.be/dmx_RFXq2nU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "地頭力を鍛える 問題解決に活かす「フェルミ推定」/後編",
      link: "https://youtu.be/6syaHtRTkiA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "イシューからはじめよ丨仕事が100分の1になる思考法",
      link: "https://youtu.be/NyhGDT26yno",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 19,
    },
    {
      title: "手軽に視座を高くする方法",
      link: "https://youtu.be/qwvbEsDbXLk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
    {
      title: "全部自分のせいにすると良いこと尽くめ",
      link: "https://youtu.be/1jbWY3K3-UA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "思考停止という病",
      link: "https://youtu.be/MLC9kwls8YI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 33,
    },
    {
      title:
        "イシューからはじめよが難しいと思っている方向け論点・イシューの出し方",
      link: "https://youtu.be/kb0O4xKT-8A",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 28,
    },
    {
      title: "なぜ「悩む力」が最強なのか？",
      link: "https://youtu.be/KEsMETo2hRU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "「空・雨・傘」理論で、無意味な資料作成から脱皮しよう！",
      link: "https://youtu.be/0JWUSfnSuD4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
    {
      title: "エッセンシャル思考①【8割捨てろ】",
      link: "https://youtu.be/BA9n_JJEcwI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "エッセンシャル思考②【見極める技術】",
      link: "https://youtu.be/rxjsGJWGTpU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
    {
      title: "エッセンシャル思考③【仕事を捨てる２STEP】",
      link: "https://youtu.be/xNk3ziBreBA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "エッセンシャル思考④【エッセンシャルなチームをつくる！若手でも】",
      link: "https://youtu.be/IwFfFZfwYP0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 26,
    },
    {
      title: "プロダクトアウトとマーケットイン",
      link: "https://youtu.be/LCruRLhXkqk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "ドリルを売るには穴を売れ",
      link: "https://youtu.be/naSs_XO1fAY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "ジョブ理論 イノベーションを予測可能にする消費のメカニズム",
      link: "https://youtu.be/Xmo8QMAotZo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 5,
    },
    {
      title: "スマートニュースが成功したマーケティング手法",
      link: "https://youtu.be/gQViWUUF_-g",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 13,
    },
    {
      title: "カスタマーサクセス",
      link: "https://youtu.be/jjq5_cROtwA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "ゼロからつくるビジネスモデル",
      link: "https://youtu.be/V3HIkZ8aVMU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "「ビジネスモデル2.0図鑑」は必見！",
      link: "https://youtu.be/0cv8IVW4Awo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "ブルー・オーシャン戦略①",
      link: "https://youtu.be/CQdoKI4ej4s",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "ブルー・オーシャン戦略②",
      link: "https://youtu.be/HeVnyud1U7Q",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "ランチェスター戦略①",
      link: "https://youtu.be/D1Tcw238Z-U",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 29,
    },
    {
      title: "ランチェスター戦略②",
      link: "https://youtu.be/zBKdqJJCbi8",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 29,
    },
    {
      title: "ストーリーとしての競争戦略",
      link: "https://youtu.be/Y-znwItNGVI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 14,
    },
    {
      title: "失敗の本質｜なぜ日本は負け続けるのか？",
      link: "https://youtu.be/8uyuz6DL0yk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "ゼロ秒思考 頭がよくなる世界一シンプルなトレーニング",
      link: "https://youtu.be/lpPDEaC1dmc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 29,
    },
    {
      title: "イノベーションのジレンマ【会社を滅ぼすのは、まさかのイノベーションでした】",
      link: "https://youtu.be/UviocRxrxkk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "ハートドリブン～目に見えないものを大切にする力 ～",
      link: "https://youtu.be/U6JE6MExyvc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
  ],
};
