import { ISection } from ".";

export const MONEY: ISection = {
  title: "超大切なお金のお話",
  description: "参考文献:",
  contentsList: [
    {
      title: "その保険、不要やで！！！～保険解約のススメとその理由～",
      link: "https://youtu.be/A66-j0z-gfA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 6,
    },
    {
      title:
        "賃貸の部屋に傷をつけてしまった時に無料で直す方法〜火災保険の補償を使って直そう！",
      link: "https://youtu.be/lRTElygyy9U",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title:
        "賃貸物件をお得に借りる方法〜見積書をチェックしてボッタクリを回避しよう！",
      link: "https://youtu.be/-dE5xRYIhNA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "住宅ローンの闇【前編】",
      link: "https://youtu.be/XRWIcqK1e8c",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title: "住宅ローンの闇【後編】",
      link: "https://youtu.be/mXiGA0u6OeY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 36,
    },
    {
      title: "歪められた福沢諭吉「学問のすすめ」の真意",
      link: "https://youtu.be/ZsYamRyLTj0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 37,
    },
    {
      title: "資本論",
      link: "https://youtu.be/B8pRw5Hj5ak",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "【金持ち父さん①】お金持ちになる手順",
      link: "https://youtu.be/57zybaVxc2o",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "【金持ち父さん②】不労所得を得るために",
      link: "https://youtu.be/1K-rjXJobxA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "【金持ち父さん③】日本のファイナンシャル・リテラシー",
      link: "https://youtu.be/0BEq6SJZDpA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "【バビロン大富豪の教え①】",
      link: "https://youtu.be/34qLgA-9oiU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 23,
    },
    {
      title: "【バビロン大富豪の教え②】",
      link: "https://youtu.be/c9qQjN4BosE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 23,
    },
    {
      title: "【バビロン大富豪の教え③】",
      link: "https://youtu.be/TxuDsrNc6ZE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "【バビロン大富豪の教え】100年間、成功し続けてる資産の作り方",
      link: "https://youtu.be/ONQe6GeyOzI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "サラリーマンの9割が豊かな老後を迎えられない理由と解決策",
      link: "https://youtu.be/W5sANNsnoVU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "【EXIT戦略①】お金持ちになる唯一の方法",
      link: "https://youtu.be/WAC0UFn02FA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "【EXIT戦略②】M&Aは今後のビジネストレンド",
      link: "https://youtu.be/4EtyvLnBdBE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "【EXIT戦略③】次世代の大富豪になる極意",
      link: "https://youtu.be/SVO1Odj-WKE​",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "【経営計画①】強いチームを作るための魔法の道具",
      link: "https://youtu.be/zQDOOq9O3Rk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 24,
    },
    {
      title: "【経営計画②】具体的な経営計画の立て方",
      link: "https://youtu.be/OGffRSsrsIQ",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title: "【経営計画③】方針を決めた後はスケジュール＆マニュアル化",
      link: "https://youtu.be/SdxbMqoCIdE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 22,
    },
    {
      title: "オープンイノベーション促進税制でスタートアップの時代到来！",
      link: "https://youtu.be/oSfdqOyLQ8U",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 5,
    },
    {
      title: "エンジニアが最も起業に向いているという話。IT企業においてエンジニア出身社長は最強",
      link: "https://youtu.be/eIiyFPPVGxM",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 12,
    },
    {
      title: "起業するためにしてきたことをまとめました！",
      link: "https://youtu.be/Xmbfx6qZQTI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title:
        "【お金の授業①】〜学校では教えてくれない「資産運用の鉄則」素人が必ずハマる罠編〜",
      link: "https://youtu.be/R_kzxTCcwbc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 30,
    },
    {
      title: "【お金の授業②】〜素人でもできる投資の鉄則を教えます〜",
      link: "https://youtu.be/t66nXm6CHPo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 28,
    },
    {
      title: "【預金か投資か①】大人も子供も知っておくべきお金の増やし方入門",
      link: "https://youtu.be/hq7EtERjXX8",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 16,
    },
    {
      title: "【預金か投資か②】低金利の銀行預金から儲かる株投資に切り替えよ",
      link: "https://youtu.be/s0GHO3XQl7I",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "【株投資①】誰でも稼げる米国株投資〜富裕層になるための鉄則〜",
      link: "https://youtu.be/MImR-ujQzzg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 26,
    },
    {
      title: "【株投資②】金が金を生む米国株高配当マネーマシンの育て方",
      link: "https://youtu.be/pTLVFx_EYqE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title:
        "【お金の守り方①】絶対にやってはいけないリボ払い・ローン・貯蓄型保険",
      link: "https://youtu.be/owgJNg4Dwv0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 22,
    },
    {
      title: "【お金の守り方②】支出の把握と貯金をしたら複利でお金持ちになろう",
      link: "https://youtu.be/H0pS2-t4pzA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 22,
    },
    {
      title: "金利のパワーについて詳しく解説",
      link: "https://youtu.be/4iwE02CTFVg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title:
        "リボ払い失敗談！ 〜たった1万円のリボ返済から6年半の借金地獄に落ちるまで〜",
      link: "https://youtu.be/LxipEVGwZsA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 8,
    },
    {
      title: "【お金の授業総まとめ①】",
      link: "https://youtu.be/bi_WFrOYhgg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "【お金の授業総まとめ②】",
      link: "https://youtu.be/X3WuBkcOw5U",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title:
        "【働かないで生きていく①】最強の早期リタイア術〜遊んで暮らして金もある〜（FIRE）",
      link: "https://youtu.be/PfLaWgQNezk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title: "【働かないで生きていく②】アメリカで話題沸騰の生き方（FIRE）",
      link: "https://youtu.be/PfLaWgQNezk",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 22,
    },
    {
      title: "【マネーマシンの作り方①】株と債券は具体的にどう買えばいいのか？",
      link: "https://youtu.be/pm2NKN_sjlA",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 28,
    },
    {
      title: "【マネーマシンの作り方②】投資のスタンダードは分散＆長期保有",
      link: "https://youtu.be/JE6YE3F67ok",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 26,
    },
    {
      title: "【お金の大学①】一生お金に困らない5つの力を身につける",
      link: "https://youtu.be/JE6YE3F67ok",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 45,
    },
    {
      title: "【お金の大学②】事業所得を稼いで投資で増やす",
      link: "https://youtu.be/GuiM0ikvJ_A",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 41,
    },
    {
      title: "インデックスファンド選びの4つのポイント【株式投資編】",
      link: "https://youtu.be/Sf5v91X6zfE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 14,
    },
    {
      title: "両学長が楽天証券を使っている3つの理由【評判GOOD】",
      link: "https://youtu.be/o-RwO6r-xEM",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 24,
    },
    {
      title: "楽天経済圏に移行して400万円分の資産所得を得る方法",
      link: "https://youtu.be/8rV9hiNxxXc",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "ふるさと納税で生活費をトコトン節約する具体的な方法",
      link: "https://youtu.be/vn8RdqwepN0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "《NISA》と《つみたてNISA》とは？",
      link: "https://youtu.be/cBcFF1fw5OY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 9,
    },
    {
      title: "【FIRE①】最速で経済的自立を実現する方法",
      link: "https://youtu.be/qDDc1pIsCFY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 28,
    },
    {
      title: "【FIRE②】収入アップと投資で早期リタイア",
      link: "https://youtu.be/bnCHUWvHC-g",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 28,
    },
    {
      title: "資産運用を始めると実感する「2つの真実」",
      link: "https://youtu.be/WcV0pCIjnzY",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 13,
    },
    {
      title: "生活費を上げずにミニマムに暮らすメリット7選",
      link: "https://youtu.be/GfKoSuJvOCQ",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 22,
    },
    {
      title: "30歳で1000万貯まる『貯金を増やすコツ5選』",
      link: "https://youtu.be/vn8RdqwepN0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 17,
    },
    {
      title:
        "ユダヤ人大富豪に教わった人生の幸福度が上がる銀行口座の使い分け方法",
      link: "https://youtu.be/hReGDOiTNAU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 14,
    },
    {
      title: "賢い人だけが知っている　自分の「本当の年収」",
      link: "https://youtu.be/F29DTP8Aulg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title:
        "21世紀の資本 byトマ・ピケティ【なぜ金持ちは金持ちなのか？→世襲資本主義】",
      link: "https://youtu.be/nxrLeco0ACg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 11,
    },
    {
      title: "日本人のためのお金の増やし方大全",
      link: "https://youtu.be/PJdCr1Fop4c",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 30,
    },
    {
      title: "お金が増える 米国株超楽ちん投資術",
      link: "https://youtu.be/G4-LB-yeUb0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 21,
    },
    {
      title: "素人でも株でお金持ちになる方法",
      link: "https://youtu.be/h9-n7aphXRI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 26,
    },
  ],
};
