import { ISection } from ".";

export const REACT: ISection = {
  title: "React",
  description:
    "Reactは世界的に人気上昇中の サイトの見た目を作るJavaScriptライブラリです。\n" +
    "本レッスンではReactに加えて、TypeScript や Firebase などについても学習します。",
  contentsList: [
    {
      title: "Reactの基礎知識",
      link: "https://youtu.be/Otrc2zAlJyM",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "Reactに欠かせないJSXの解説",
      link: "https://youtu.be/FuYdTDx8ZP4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "React I",
      link: "https://prog-8.com/lessons/react/study/1",
      mediaType: [],
      requiredTime: 100,
    },
    {
      title: "VS Codeの使い方講座！日本語化する拡張機能のインストールも紹介！",
      link: "https://youtu.be/csOaPNMDEwg",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 30,
    },
    {
      title: "VS Code ショートカット",
      link: "https://youtu.be/cNyvefTJOcM",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 35,
    },
    {
      title: "Prettierの使い方解説",
      link: "https://youtu.be/zoaIv5ifoPI",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
    {
      title: "コマンドライン",
      link: "https://prog-8.com/languages/commandline",
      mediaType: [],
      requiredTime: 65,
    },
    {
      title: "Gitを学ぼう",
      link: "https://ferret-plus.com/6104",
      mediaType: [],
      requiredTime: 60,
    },
    {
      title: "知っておいて損はなし！新人Webデザイナーのための「npm」入門",
      link: "https://ferret-plus.com/6104",
      mediaType: ["READ_ONLY"],
      requiredTime: 15,
    },
    {
      title: "create-react-appで環境構築しよう",
      link: "https://youtu.be/P5lDbRxp9sI",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 100,
    },
    {
      title: "コンポーネント間でデータの受け渡しと再利用をしよう",
      link: "https://youtu.be/xhVcWoHAyTs",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 60,
    },
    {
      title: "コンポーネントのstateの設定・取得・変更",
      link: "https://youtu.be/j4t0aZge0Mc",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 40,
    },
    {
      title: "ライフサイクルの流れを理解しよう",
      link: "https://youtu.be/2jRkPz4-hSo",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 50,
    },
    {
      title: "importとexportでモジュールを使いこなそう",
      link: "https://youtu.be/OHMDMixkVHk",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 40,
    },
    {
      title: "React Hooksでstateを扱おう",
      link: "https://youtu.be/Vzvbke_CLAs",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 40,
    },
    {
      title: "関数コンポーネントでライフサイクルを扱おう",
      link: "https://youtu.be/WrOzSzt6u3c",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 50,
    },
    {
      title: "はじめてのReact",
      link: "https://codeprep.jp/books/104",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "Reactで作るTodoアプリ",
      link: "https://codeprep.jp/books/116",
      mediaType: [],
      requiredTime: 20,
    },
    {
      title: "Reactハンズオン~ 簡単なToDoアプリ作成 ~",
      link:
        "https://docs.google.com/presentation/d/1a9xbOO22ZAHJqGvUyOTRAT-E3ndMxnwRhNHNjNot7RA/edit?usp=sharing",
      mediaType: ["USE_GIT", "USE_MY_PC"],
      requiredTime: 240,
    },
    {
      title: "npmとは yarnとは",
      link: "https://qiita.com/Hai-dozo/items/90b852ac29b79a7ea02b",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "npmとyarnのコマンド早見表",
      link: "https://qiita.com/Hai-dozo/items/1696530bb9fd59aa28d8",
      mediaType: ["READ_ONLY"],
      requiredTime: 10,
    },
    {
      title: "React 入門 #1 - Reactの新規プロジェクト立ち上げ",
      link: "https://youtu.be/lEEC_NuIGQc",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 50,
    },
    {
      title:
        "React 入門 #2 - コンポーネントのプロパティ(props)とステート(state)",
      link: "https://youtu.be/8KV1CBcB2Yg",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 40,
    },
    {
      title:
        "React 入門 #3 - Class Components と Function Components の書き方の違い",
      link: "https://youtu.be/ve85ejcYiZ0",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 40,
    },
    {
      title: "React 入門 #4 - 条件分岐 (if) と繰り返し (loop)",
      link: "https://youtu.be/ZLEMN2pCE8E",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 40,
    },
    {
      title: "React 入門 #5 - フォームと親子間のデータのやり取り",
      link: "https://youtu.be/kEBP9WhifX0",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 60,
    },
    {
      title: "React 入門 #6 - コンポーネントのライフサイクル",
      link: "https://youtu.be/SKrnW7PRBdk",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 60,
    },
    {
      title: "React 入門 #7 - Reactのスタイル",
      link: "https://youtu.be/VxwI2tavv_M",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 60,
    },
    {
      title: "React 入門 #8 - Higher-Order Component",
      link: "https://youtu.be/9iulWDK95TY",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 60,
    },
    {
      title: "React 入門 #9 - Portalを利用したモーダル",
      link: "https://youtu.be/Kx3cOJWXS8c",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 60,
    },
    {
      title: "React 入門 #10 - refによるエレメントの取得",
      link: "https://youtu.be/j-c7qQNNRa8",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 60,
    },
    {
      title: "React 入門 #11 - Contextを利用したテーマの変更",
      link: "https://youtu.be/cYa8-3lfCn4",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 90,
    },
    {
      title: "React 総復習！ Reactの大事な部分を紹介します！！",
      link: "https://youtu.be/VRbEqvneqL4",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "アトミックデザインのすゝめ",
      link: "https://www.youtube.com/watch?v=Un0aoW0kNeE",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title: "頼むからエンジニアは全員『リーダブルコード』を読んでくれ",
      link: "https://youtu.be/XZKgdM5x_ds",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "プログラムにマジックナンバーを使うべきでない理由を解説しよう",
      link: "https://youtu.be/OnTtXy6x3ZU",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 15,
    },
    {
      title: "JavaScriptのコーディングルールを決めよう",
      link: "https://youtu.be/12gb3pCuzV4",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "最速で学ぶTypeScript",
      link: "https://www.udemy.com/course/typescript-react-frontend/",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 110,
    },
    {
      title: "最速で学ぶFirebase + React Hooks (TypeScript)",
      link: "https://www.udemy.com/course/firebasereact-hookstypescript-todo/",
      mediaType: ["USE_GIT", "USE_MY_PC", "VIDEO"],
      requiredTime: 400,
    },
    {
      title: "React.memoによるパフォーマンスチューニング",
      link: "https://youtu.be/s6HThFCXgsw",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 20,
    },
    {
      title: "Hooks時代のパフォーマンスチューニング",
      link: "https://youtu.be/cNDEUPeOJTo",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 25,
    },
    {
      title: "Webの技術でアプリが作れる、ReactNative入門",
      link: "https://youtu.be/_AKJE0vB-z0",
      mediaType: ["READ_ONLY", "VIDEO"],
      requiredTime: 10,
    },
  ],
};
